language: node_js
node_js:
  - '7'
services:
  - mongodb
addons:
  code_climate:
    repo_token: '9ad8b6bc7cc0a2170247509565f96d4fcde92aca850f117699e24831102e9880'
notifications:
  email: false
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
